ui: tape
capabilities:
  record-video: false
  video-upload-on-pass: false
  record-screenshots: false
  max-duration: 1800
  command-timeout: 400
  idle-timeout: 200
browsers:
  - name: ie
    version: 10..latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: opera
    version: latest
  - name: chrome
    version: latest
  - name: ipad
    version: 7.1..latest
  - name: iphone
    version: 7.1..latest
