ui: tape
capabilities:
  record-video: false
  video-upload-on-pass: false
  record-screenshots: false
tunnel:
  type: ngrok
  bind_tls: true
browsers:
  - name: microsoftedge
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: chrome
    version: latest
  - name: iphone
    version: latest
  - name: android
    version: latest
